wlcore-objs		= main.o mac80211_ops.o

#wlcore_spi-objs 	= spi.o
#wlcore_sdio-objs	= sdio.o

obj-$(CONFIG_WLCORE)			+= wlcore.o
#obj-$(CONFIG_WLCORE_SPI)		+= wlcore_spi.o
#obj-$(CONFIG_WLCORE_SDIO)		+= wlcore_sdio.o

# small builtin driver bit
#obj-$(CONFIG_WLCORE_PLATFORM_DATA)	+= wlcore_platform_data.o
